version: '3.8'
services:
  lorescribe:
    build: 
      context: .
      target: builder  # Use the builder stage for development
    platform: linux/amd64
    deploy:
      resources:
        limits:
          memory: 16G
          cpus: '4'
        reservations:
          memory: 16G
    environment:
      NODE_ENV: development
      PORT: 8080
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TLS_ENABLED: "false"
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - recordings:/recordings
    depends_on:
      redis:
        condition: service_healthy
    command: ["pnpm", "start"]  # Use the start script from package.json

  redis:
    image: redis:7-alpine
    platform: linux/amd64
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis_data:
  recordings:
