version: '3.8'
services:
  bot:
    build: .
    platform: linux/amd64
    deploy:
      resources:
        limits:
          memory: 16G
          cpus: '4'
        reservations:
          memory: 16G
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/usr/src/app
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    platform: linux/amd64
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis_data:
