name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
      - develop
      - staging
      - CustomizePromptDeletePrompt
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd ~/SummarizerBot
            git fetch origin
            git checkout ${{ github.event.inputs.branch || github.ref_name }}
            git pull origin ${{ github.event.inputs.branch || github.ref_name }}
            pm2 restart summarizer-bot 